### ISSUE TITLE
External IP constraint doesn't detect ephemeral IPs

### ISSUE THREAD

**Issue by morgante** [forseti-security/policy-library#10]
Currently, if you create a new VM with an external IP via Terraform with an ephemeral IP the constraint doesn't violate.

**Comment by AdrienWalkowiak** [comment]
Is it still the case? If not, what can be done about it?

**Comment by morgante** [comment]
Yes looks like it's still there: https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_compute_external_ip_access_v1.yaml#L75

We would need to update this to:
1. Look at the *plural* for network interfaces
2. Not look at the external IP itself

**Comment by morgante** [comment]
https://github.com/forseti-security/policy-library/pull/128 is meant to address this
