### ISSUE TITLE
Add Firewall template

### ISSUE THREAD

**Issue by mldmld68** [forseti-security/policy-library#112]
Hi all,
Please add firewall and constraint sample policies to check 
- if an SA can talk to another SA based on a regex on their names
- if TCP 22 or 3389 is opened to 0.0.0.0/0
- if TCP open ports specify a wide range : [1-65535] 
- if a range of subnets are the only one allowed for ingress
 
Thank you
Best regards

**Comment by AdrienWalkowiak** [comment]
Hi, I am currently on getting this policy released. I don't have an ETA yet, but I hope it will be soon-ish.

**Comment by AdrienWalkowiak** [comment]
I opened a #158 for this constraint but it needs more in-depth testing considering the scope of this policy. I am worried about performance issues with forseti or even locally on large datasets.

**Comment by gkowalski-google** [comment]
The firewall template is now available: https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_restricted_firewall_rules_v1.yaml.
