### ISSUE TITLE
GCS Blacklist Public - Not Triggering

### ISSUE THREAD

**Issue by jdyke** [forseti-security/policy-library#114]
I have tried a couple different ways to trigger the example policy located in **policy-library/samples/storage_blacklist_public.yaml** but am having no luck. The rego inside **policy-library/policies/templates/gcp_storage_bucket_world_readable_v1.yaml** is looking for

```
constraint := input.constraint
           	asset := input.asset
           	asset.asset_type == "storage.googleapis.com/Bucket"
           
           	world_readable_checks := [
           		asset.iam_policy.bindings[_].members[_] == "allUsers",
           		asset.iam_policy.bindings[_].members[_] == "allAuthenticatedUsers",
           	]
           
           	world_readable_checks[_] == true
```
Some of the example terraform code used to try and violate the constraint is:

```
variable "project" { }

provider "google" {
  project = "${var.project}"
}


resource "google_storage_bucket" "test-1" {
  name     = "test-1"
  }

resource "google_storage_bucket" "test-2" {
  name     = "test-2"
  }

  resource "google_storage_bucket_iam_policy" "member" {
  bucket = "${google_storage_bucket.test-1.name}"
  policy_data = "${data.google_iam_policy.foo-policy.policy_data}"
}


data "google_iam_policy" "foo-policy" {
  binding {
    role = "roles/storage.objectViewer"

    members = [
      "allUsers",
      "allAuthenticatedUsers",
    ]
  }
}

resource "google_storage_bucket_iam_binding" "binding1" {
  bucket = "${google_storage_bucket.test-2.name}"
  role        = "roles/storage.objectViewer"

  members = [
      "allUsers",
      "allAuthenticatedUsers",
    ]
}

resource "google_project_iam_policy" "project" {
  project = "${var.project}"
  policy_data = "${data.google_iam_policy.foo-policy.policy_data}"
}
```

This main.tf successfully creates two public buckets with IAM permissions attached for public read.

**Comment by morgante** [comment]
I suspect this is an issue with Terraform Validator.

Can you confirm if this issue occurs when using Forseti?

**Comment by jdyke** [comment]
Does not look like it as first glance:

```
{
  "serverMessage": "Resource 'config_validator_violations' has no violations"
}
```

```
~/forseti-security/policy-library/policies/constraints$ pwd
/home/ubuntu/forseti-security/policy-library/policies/constraints
~/forseti-security/policy-library/policies/constraints$ ll
total 16
drwxr-xr-x 2 root root 4096 Jul 12 18:11 ./
drwxr-xr-x 4 root root 4096 Jul 12 18:11 ../
-rw-r--r-- 1 root root  193 Jul 12 18:11 README.md
-rw-r--r-- 1 root root  362 Jul 12 18:11 storage_blacklist_public.yaml
```

**Comment by jdyke** [comment]
Bucket:

```
gsutil iam get gs://<bucketname>
{
  "bindings": [
    {
      "members": [
        "allAuthenticatedUsers",
        "allUsers"
      ],
      "role": "roles/storage.objectViewer"
    }
  ],
  "etag": "CAI="
}
```

**Comment by joecheuk** [comment]
Hi Jason,

Can you check the forseti server config file and see if config validator
scanner is enabled?

The config file is located at
forseti-security/configs/forseti_conf_server.yaml

If you navigate under section `scanners`, there is one for
config-validator, can you double check and see if it's enabled?

Thanks,
Joe

**Comment by jdyke** [comment]
Yeah its there:

```
- name: config_validator
          enabled: true
```

**Comment by jdyke** [comment]
Joe was able to get the constraint working with forseti and I'll continue to troubleshoot on my end why it isnt working. Probably a setup challenge. In the meantime, @morgante do you have what you need to troubleshoot the validator code?

Thanks

**Comment by morgante** [comment]
Yeah, I was able to validate this works with Config Validator and can look into why it's not working with Terraform specifically.

**Comment by morgante** [comment]
So there are issues at play here:
- The examples using 'google_storage_bucket_iam_policy' and 'google_storage_bucket_iam_binding' don't work with Terraform Validator because Terraform Validator doesn't parse bucket policies. I opened #52 to track. They *will* trigger a violation in Forseti or other implementations though.
- The example using google_project_iam_policy won't work because it sets an IAM policy for the project not the folder. Currently our constraints don't look at inherited policies—they probably should.

**Comment by jdyke** [comment]
Thanks Morgante. #52 is about encryption - is that the correct number?

**Comment by jdyke** [comment]
Found it on the other repo: https://github.com/GoogleCloudPlatform/terraform-validator/issues/52

**Comment by FanchenBao** [comment]
This is probably because when terraform-validator convert the Terraform plan to CAI, it omits the resources that it currently doesn't support (see `terraform-validator convert --help`). Since `google_storage_bucket_iam_binding` and `google_project_iam_policy` are not supported, they will not be present in the CAI file. And since the validator rego code pulls info from the CAI file, `asset.iam_policy.bindings[_].members[_]` returns null and the rule evaluates to false, or no violation.

**Comment by morgante** [comment]
@FanchenBao Precisely. Once https://github.com/GoogleCloudPlatform/terraform-validator/issues/52 is fixed, this will be too.
