### ISSUE TITLE
Terraform Validator Source Code ?

### ISSUE THREAD

**Issue by Abdennebi** [forseti-security/policy-library#17]
In the [user guide](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md) you are referring to the Terraform Validator Tool, is its code source available ?

**Comment by morgante** [comment]
Yes! It is open source and available [here](https://github.com/GoogleCloudPlatform/terraform-validator).

**Comment by Abdennebi** [comment]
Thank you ! I missed it 😅
