### ISSUE TITLE
Update Forseti CV documentation

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/policy-library#181]
- [ ] Review current CV docs about scaling
- [ ] Update or remove content that is outdated or has changed.

I don't think this data is up to date with core Forseti configurations as of late. I believe we have increased the standard VM sizes by default. Also there is work to page data into CV from Forseti which is to be released soon.

Can you please review the content here and ensure it is accurate or can be removed.

https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-handle-scaling-for-large-resource-sets

How to handle scaling for large resource sets
If you want to scale for large resource sets, you need to add more RAM to your server**.** Upgrading the Forseti server VM to n1-standard-4 (15GB of RAM) should be able to handle most use cases. Depending on the state and size of your data, this may trigger a large number of violations. Currently GRPC has a payload size limitation of 4MB. If a scanner run results in > 4MB of violation data to be generated, that will result in an error.

In the future, we will consider the following changes:
Use streaming GRPC or paging the violation results.
Split the dataset into multiple chunks and process them separately.

**Comment by red2k18** [comment]
The information here is inaccurate. `n1-standard-8` (30 GB of RAM) machine type is needed to account for larger GCP environments. 

This information [is accurately documented on the Forseti website](https://forsetisecurity.org/docs/latest/setup/install/index.html) and no longer exists on the Policy Library repository. Hence, this issue can be closed.
