### ISSUE TITLE
Centralize the Documentation on the forsetisecurity.org Website

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/policy-library#185]
We should consider migrating the [User Guide](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md) and all documentations from the repo markdowns to the [forsetisecurity.org](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md) so that all documentations are centralized and easy for users to find & follow end-to-end.

**Comment by morgante** [comment]
The User Guide is not only for Forseti. We could move the Forseti guide over, but the other user guides should be kept separate (or separately usable).

**Comment by gkowalski-google** [comment]
> The User Guide is not only for Forseti. We could move the Forseti guide over, but the other user guides should be kept separate (or separately usable).

Agree, I will only move the Forseti specific documentation to the website.

**Comment by gkowalski-google** [comment]
Move the [CSCC](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-connect-violation-results-with-cloud-security-command-center-cscc) instructions to the website.
