### ISSUE TITLE
Make it easy to identify which policies are usable by which clients.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/policy-library#186]
Currently, not all the policies are usable by Forseti.  And it's not easy to tell which ones they are.  It would be awesome if there's a way to identify which policies are usable by which clients.

One idea is to maintain a running list of the supported policies in the documentation.

Another idea would be to rely on the bundle-pulling tool, and show which policies would be pulled.
This tool is here: https://github.com/forseti-security/config-validator/tree/master/cmd/policy-tool

**Comment by gkowalski-google** [comment]
The policies are now documented within the [Policy Library](https://github.com/forseti-security/policy-library/blob/master/docs/index.md) and a [KPT function is available to pull a policy bundle](https://github.com/forseti-security/policy-library/blob/master/docs/kpt_functions.md).
