### ISSUE TITLE
Make the Options for Policy Library Sync to Be Consistent

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/policy-library#190]
On GCE, this is off by default, and needs `policy_library_sync_enabled = true` to be set.

On GKE, this is on by default, and `policy_library_sync_enabled` is not exposed to be configure-able.

Since there is a case for continued usage of GCS buckets, a couple of things need to be done:
1: `policy_library_sync_enabled` needs to be configure-able on GKE in case GCS is prefered
2: make consistent the default behavior whether it's on or off, on both GCE and GKE

**Comment by dekuhn** [comment]
Issue moved to [forseti-security/terraform-google-forseti #341](https://github.com/forseti-security/terraform-google-forseti/issues/341) via [**ZenHub**](https://www.zenhub.com/)
