### ISSUE TITLE
Add policy linter to cloudbuild CI steps

### ISSUE THREAD

**Issue by briantkennedy** [forseti-security/policy-library#257]
[FCV](https://github.com/forseti-security/config-validator) now has a rule for [generating a policy tool docker image](https://github.com/forseti-security/config-validator/blob/master/Makefile#L490.  We should set up the cloud build image for policy-library to use the linter on new policies.

**Comment by blueandgold** [comment]
Additional details per brian: this is a linter from brian for ConstraintTemplates and Constraints, but need to be added to the test / CI process for policy-library.

**Comment by briantkennedy** [comment]
In the time this has been open, a broken template got in during commit  b7c46f70f2f213b20d488a3a7a4431bc1724419f.  Can we prioritize this issue as it's been open for quite some time now.
