### ISSUE TITLE
Update glob.match calls to specify delimiter

### ISSUE THREAD

**Issue by tsandall** [forseti-security/policy-library#258]
The latest minor release of OPA (v0.17) fixes an issue in the `glob.match` built-in function. Basically the built-in function was supposed to default the delimiter to `.`...but it wasn't. I did a search of public repos on GitHub and noticed two cases here. The fix is to simply update the `glob.match` built-in function calls to supply `["/"]` for the delimiter. We try to avoid backwards incompatible changes as much as possible but in this case it felt like it was better to fix the buggy built-in rather than deprecating it and introducing a new one.

cc @morgante

**Comment by morgante** [comment]
Thanks for letting us know, I assume these are the two cases you found?

- https://github.com/forseti-security/policy-library/blob/a069b66f9cff36bc38a4c858bf3d788b29d61b4b/validator/iam_allowed_bindings.rego#L35
- https://github.com/forseti-security/policy-library/blob/73e19dda7dbbf89a633308adf524d47d253301c4/validator/iam_allow_ban_roles.rego#L32

In both cases, we're explicitly passing a `[]` delimiter list (to avoid having any delimiters). Will this change/break?

**Comment by tsandall** [comment]
Yep, those are the cases. I looked at the constraint parameters and assumed that you were intending to use `/` as the delimiter. What is the glob match behaviour that you want? If the current (fixed) built-in doesn't work for you use case, we can introduce another one.

**Comment by morgante** [comment]
In this case, I don't think we actually need any delimiter matching. You can see some sample params [here](https://github.com/forseti-security/policy-library/blob/master/samples/iam_allowed_roles.yaml#L29) and in those cases we're providing the full desired role (potentially with a wildcard).

**Comment by tsandall** [comment]
Fair enough. I think the update to specify the "/" delimiter will work for your use cases. If you can have roles with multiple "/" characters in them you could use the super glob: https://www.openpolicyagent.org/docs/latest/policy-reference/#glob. Alternatively, if you just want exact matching and prefix matching (indicated w/ wildcard) you _could_ implement that inside of Rego today. Hope this helps.

**Comment by AdrienWalkowiak** [comment]
this policy tests actually break when using opa 0.17, probably because of this issue.

@FanchenBao can you take a look?

**Comment by FanchenBao** [comment]
@AdrienWalkowiak Sure. Looking into it now.

**Comment by FanchenBao** [comment]
@AdrienWalkowiak  @morgante A PR has been submitted for the bug fix: #260 
I also wrote a bug fix report as comment for the PR.
