### ISSUE TITLE
[FORSETI] Cloud SQL scanner functionality

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/policy-library#264]
Related to Forseti Security Issue [#3624](https://github.com/forseti-security/forseti-security/issues/3624)

### Scanner

Cloud SQL Scanner

**Description:** Cloud SQL instances can be configured to grant external networks access. The Cloud SQL scanner supports a blacklist mode, to ensure unauthorized users don’t gain access to your Cloud SQL instances.

### Python Violations Summary
Generate a violation if any of the following fields do not match:

- Instance_name
- Authorized_networks
- Require_ssl

### 1:1 Rego | Python Parity Status
It looks like the Rego rule does check for authorized_networks and require_ssl, but it does not check for the instance_name.

### Rego work to do
Create or edit existing Rego rules to do the following:

- https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_sql_allowed_authorized_networks_v1.yaml

- https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_sql_ssl_v1.yaml

1) Allow to check for instance name parameter --> currently only looks at authorized_networks and require_ssl.

**Comment by gkowalski-google** [comment]
Does [this policy](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_sql_ssl_v1.yaml) cover the check for requiring SSL?

**Comment by hshin-g** [comment]
Looks like it- thanks Gregg!

**Comment by morgante** [comment]
For instance name checking, I think this should cover it: https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_enforce_naming_v1.yaml

**Comment by hshin-g** [comment]
The Forseti scanner allows you to target specific instances to check if SSL is disabled or has a public IP. The Rego template that exists follows best practices to check all instances.
