### ISSUE TITLE
[FORSETI] Kubernetes Engine scanner functionality

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/policy-library#269]
Related to Forseti Security Issue [#3624](https://github.com/forseti-security/forseti-security/issues/3624)

### Scanner

Kubernetes Engine Scanner

**Description:** "Kubernetes Engine clusters have a wide-variety of options. You might want to have standards so your clusters are deployed in a uniform fashion. Some of the options can introduce unnecessary security risks. The KE scanner allows you to write rules that check arbitrary cluster properties for violations. It supports the following features:

- Any cluster property can be checked in a rule by providing a JMESPath expression that extracts the right fields.See http://jmespath.org/ for a tutorial and detailed specifications.
- Rules can be whitelists or a blacklists.

### Python Violations Summary
There are two types (modes) that can generate violations:

1) **Whitelist** - generate a violation if value extracted is NOT in the list defined in ke_scanner_rules.yaml file.

2) **Blacklist** - generate a violation if value extracted IS in the listed defined in ke_scanner_rules.yaml file.

**Whitelist**

For each rule that a user has defined in the ke_scanner_rules.yaml file, there will be a “key” field that maps to a KeCluster property (e.g. loggingService). For each KeCluster, search for that “key” field in the KeCluster.data (e.g. look for the “loggingService” field). If this field exists, compare the value of the field against the list of “values” defined in the ke_scanner_rules.yaml file. If the value does NOT exist, generate a violation (as it is not a whitelisted value).

**Blacklist**

For each rule that a user has defined in the ke_scanner_rules.yaml file, there will be a “key” field that maps to a KeCluster property (e.g. loggingService). For each KeCluster, search for that “key” field in the KeCluster.data (e.g. look for the “loggingService” field). If this field exists, compare the value of the field against the list of “values” defined in the ke_scanner_rules.yaml file. If the value DOES exist, generate a violation (as it is a blacklisted value).

### 1:1 Rego | Python Parity Status
There does not seem to be any Rego policies related to GKE whitelisting/blacklisting cluster properties. Will need to create this functionality. This does NOT seem to require the use of the Service Config resource that is currently not available in CAI and seems to only use the Cluster resource which is available in CAI. 

### Rego work to do

Create Rego rule(s) to do the following:

1) Create a sample constraint for whitelist/blacklist utilizing the generic constraint template #198

**Comment by morgante** [comment]
Generic constraint template: https://github.com/forseti-security/policy-library/pull/198

**Comment by hshin-g** [comment]
Verify that the PR above works and fulfills this use case.

**Comment by hshin-g** [comment]
Provide a sample constraint for this.
