### ISSUE TITLE
Add KMS sample for Forseti bundle

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/policy-library#317]
Forseti checks for crypto keys that are older than 100 days. The policy library contains a sample checking for 365 days. In order to switch over, we want to provide a policy that has the same behavior. Add a sample for this.

**Comment by morgante** [comment]
I think it would be fine to change the existing sample to 365 days.

**Comment by gkowalski-google** [comment]
> I think it would be fine to change the existing sample to 365 days.

Thanks, I considered it, but that [one is part of a CIS benchmark](https://github.com/forseti-security/policy-library/blob/master/samples/cmek_rotation.yaml). I know it's kind of silly to have 2, but want to make sure the default behavior remains the same out of the box with Forseti. And I need to have a sample in order to pull in the policy bundle easily with KPT.

**Comment by morgante** [comment]
Do you know if the CIS benchmark actually requires this period though, or just the existence of one?

I'm fine with making a separate one if you want though.

**Comment by gkowalski-google** [comment]
I reviewed the CIS benchmark and it looks like it was updated in v1.1 to require the CMEK to be rotated within 365 days. Forseti has defaulted to scanning for 100 days, will submit a PR for a new sample.
