### ISSUE TITLE
Change to more inclusive language

### ISSUE THREAD

**Issue by morgante** [forseti-security/policy-library#362]
The terms "blacklist" and "whitelist" are [unrecommended](https://developers.google.com/style/inclusive-documentation#features-and-users).

We currently have [55 instances](https://github.com/forseti-security/policy-library/search?q=blacklist&unscoped_q=blacklist) of `blacklist` and [68 instances](https://github.com/forseti-security/policy-library/search?q=whitelist) of `whitelist` which we should consider changing. In most cases, `denylist` and `allowlist` are descriptive alternatives.

Let's also make sure that new constraints use inclusive language and ideally have a reference in developer documentation.

**Comment by briantkennedy** [comment]
Adding the type to the field name gets a bit redundant while reading the field, let's go for `deny` and `allow`.
