### ISSUE TITLE
storage location policy: violations is not reported when exemptions list is not specified

### ISSUE THREAD

**Issue by xingao267** [forseti-security/policy-library#369]
Adding `exemptions: []` would make it work, but it's a little counter-intuitive.

**Comment by morgante** [comment]
We should update https://github.com/forseti-security/policy-library/blob/master/validator/storage_location.rego#L32 to use `get_default`.

**Comment by xingao267** [comment]
just tested bq dataset location has the same issue.

**Comment by xingao267** [comment]
and sql location
