### ISSUE TITLE
make generate_docs generates `EACCES: permission denied` error

### ISSUE THREAD

**Issue by xingao267** [forseti-security/policy-library#375]
At commit ccab976557943550d764659abce52372ecaba94d

```
$ make generate_docs 
Generating docs with kpt...
Error: EACCES: permission denied, stat '/docs/func.yaml'
make: *** [Makefile:147: generate_docs] Error 2
```

**Comment by gkowalski-google** [comment]
@xingao267 Can you take a look at what the permissions are for `/docs/func.yaml`?

**Comment by xingao267** [comment]
I do have write permission on the file.
```
$ ls -la docs/func.yaml 
-rw-rw-rw- 1 xingao primarygroup 1054 Sep 11 15:35 docs/func.yaml
```

It seems the permission issue is from within the container.

**Comment by xingao267** [comment]
The cause is the generate_docs container sets the default user to be [`node`](https://github.com/forseti-security/policy-library/blob/master/bundler/build/generate_docs.Dockerfile#L27), which does not have `write` permission to the files under `docs` dir by default when those files are mounted into the container. I bypassed it by adding `-u root` in the `docker run` command in the `make generate_docs` command.

**Comment by xingao267** [comment]
I'm still getting this error. The generate doc dev container needs to be rebuilt and published i guess.

**Comment by gkowalski-google** [comment]
The updated docker image was successfully built and published on Friday.
