### ISSUE TITLE
How to add a new policy bundle

### ISSUE THREAD

**Issue by xingao267** [forseti-security/policy-library#376]
Is there any existing instructions around the process of how to add a new policy bundle? I'm working on adding a healthcare-best-practices policy bundle. And based on my guesses, I just add a new entry to the policy sample that I would like to include in the bundle, e.g. in `samples/storage_location.yaml`'s `metadata.annotations` list, I added line `bundles.validator.forsetisecurity.org/healthcare-best-practices-v1: security`. Am I on the right track? After I do that, how do I update all other docs and references? I guess `make generate_docs`?

**Comment by xingao267** [comment]
@morgante @gkowalski-google any guidance here?

**Comment by morgante** [comment]
@xingao267 Yes you just need to add the annotation on the resources + run `make generate_docs`.

**Comment by xingao267** [comment]
@morgante thanks! I hit this error when trying to run `make generate_docs` though https://github.com/forseti-security/policy-library/issues/375

**Comment by gkowalski-google** [comment]
It looks like it's just a permissions issue, can you take a look and see if you have write permissions to that file?
