### ISSUE TITLE
Config validator is too verbose

### ISSUE THREAD

**Issue by vvdaal** [forseti-security/policy-library#387]
On the current master branch I noticed that config validator in the service initialize script is too verbose. Since this is a threaded program itll fill your syslog and cloud logs quite quickly.

**Comment by morgante** [comment]
Please file these sorts of issue with Forseti: https://github.com/forseti-security/forseti-security

This isn't an issue with the policies.

**Comment by vvdaal** [comment]
My bad! Wrong repo :-)
