### ISSUE TITLE
The policy "storage bucket policy only" is using deprecated argument bucketPolicyOnly

### ISSUE THREAD

**Issue by daniel-cit** [forseti-security/policy-library#388]
`gcp_storage_bucket_policy_only_v1.yaml` and `storage_bucket_policy_only.rego` are using only the deprecated argument `bucketPolicyOnly` in the validation:

https://github.com/forseti-security/policy-library/blob/73fdd2fee8f9aa71f66e6cc1d1c781a712f6cf73/policies/templates/gcp_storage_bucket_policy_only_v1.yaml#L79

https://github.com/forseti-security/policy-library/blob/73fdd2fee8f9aa71f66e6cc1d1c781a712f6cf73/validator/storage_bucket_policy_only.rego#L41

They should be checking for both `bucketPolicyOnly`  and  `UniformBucketLevelAccess` in this validation until `bucketPolicyOnly` is removed in the next major release of the provider.

**Comment by daniel-cit** [comment]
One option would be to create an `gcp_storage_bucket_policy_only`  **version 2** that uses the new argument `UniformBucketLevelAccess`

**Comment by morgante** [comment]
I believe the best approach would actually be to update the policy so it looks for either UniformBucketlevelAccess or bucketPolicyOnly.

**Comment by daniel-cit** [comment]
Related issue in terraform-google-conversion https://github.com/GoogleCloudPlatform/terraform-google-conversion/issues/591
