### ISSUE TITLE
Modifying fixture library likely to affect multiple constraint templates

### ISSUE THREAD

**Issue by ddremund** [forseti-security/policy-library#63]
It appears that as the test fixtures are maintained today, the typical constraint template test often includes counting "denies" produced against the entirety of the asset fixtures for a particular resource type or set of resource types.

It seems likely that in many cases, producing new asset fixtures as required for testing newly-developed policies has the side effect of also modifying the fixture library used for testing existing policies, which may break their tests, requiring the developer of a new constraint to either spend time crafting fixtures that meet previous expectations of other constraint tests, or modify those tests (from other fixtures than they were working on in their branch) to account for the newly added fixtures.

Should we consider changing the paradigm such that there is a default set of fixtures, and then perhaps a subdirectory for constraint-specific fixtures? I considered implementing this myself for a policy PR I recently submitted, but thought maybe it should be raised as an issue first.

**Comment by t12g** [comment]
Thanks for bringing this up. Sharing test data between different constraint templates doesn't seem sustainable to me either. I'd suggest taking it one step further - is there a strong reason to have a common set of test fixtures? Maybe we should make every constraint template test to have its own private set of test data?

There will be some duplication, but it's just data, not logic. The benefit is that we'll never have to worry about whether modifying a test fixture will break other tests. Thoughts? @morgante - I'd like to get your take on this as well.

**Comment by ddremund** [comment]
@t12g You're right, there would be some duplication but it is just data. I think that would vastly simplify things.

**Comment by morgante** [comment]
> Maybe we should make every constraint template test to have its own private set of test data?

I agree, I'd suggest we change the fixtures to be constraint-specific.

**Comment by ddremund** [comment]
It looks like some authors are creating their own fixture sets, some are using existing ones, and some are mixing the two. A standardized directory structure would be desirable, e.g. fixtures/<constraint-name>/<asset-type> or fixtures/<asset-type>/<constraint-name>. I prefer the former, myself.

**Comment by morgante** [comment]
I think `fixtures/<asset-type>/<constraint-name>` is preferable.

**Comment by ddremund** [comment]
I'm cool with `fixtures/<asset-type>/<constraint-name>`. I guess the good thing about that is it makes it easy for us to pre-create a directory structure for folks to drop their stuff in.

Once my two outstanding PRs are in I'll see what I can do with regard to creating the structure and patching some of the existing constraint tests.

**Comment by morgante** [comment]
Excellent, thanks.

**Comment by abombss** [comment]
@t12g I have to cleanup my test data for #76 and I just wanted to confirm what the right approach and standard should be.  My constraint is generic, it can operate on any asset type and multiple asset types so it doesn't comply well to `<asset-type>` convention above.

I was thinking something like this, to keep the data with the constraint.

```
fixtures/<constraint-name>/<scenario?>/assets/data.json
fixtures/<constraint-name>/<scenario?>/constraints/data.yaml
```
So looking at #72 instead of creating a huge number constraints in the fixtures directory all the asset data and constraints could be isolated under a single spot.  It would also make it easier to version the tests along with the constraints assuming when V2 comes, we are still keeping the legacy tests in place for V1.

```
fixtures/GCPBigQueryDatasetLocationConstraintV1/assets/data.json
fixtures/GCPBigQueryDatasetLocationConstraintV1/constraints/allowlist_all/data.yaml
fixtures/GCPBigQueryDatasetLocationConstraintV1/constraints/allowlist_one/data.yaml
```

**Comment by ddremund** [comment]
@abombss I like this approach. If the particular constraint needs to separate out asset fixtures by type in json files (for some reason), they can just do `<constraint-name>/assets/<asset-type>/data.json, otherwise they can just keep the json directly in `assets`. This also makes it fairly easy to patch the existing constraints.

**Comment by morgante** [comment]
That SGTM.

**Comment by abombss** [comment]
Cool, I'll use this approach for #76 then we can see about migrating the existing stuff.

**Comment by ddremund** [comment]
@abombss I realize that, but I can imagine cases in which someone might prefer to import different classes into separate collections without having to inspect and split the data. Just mentioning that that capability would still exist.

I'll go ahead and adapt the constraint templates I authored to this new fixtures structure.

**Comment by morgante** [comment]
I like the idea of organizing asset and constraint fixtures together in a single directory for each template.

So, something like what @abombss proposed:

```
fixtures/bq_dataset_location/assets/data.json
fixtures/bq_dataset_location/constraints/allowlist_all/data.yaml
fixtures/bq_dataset_location/constraints/allowlist_one/data.yaml
```

**Comment by ddremund** [comment]
I agree with the overall organization strategy. I also aesthetically prefer the shorter name matching with the rule filename.

Do we want name-based version semantics in the fixtures? Using the full constraint name ensures that versioning enforced/maintained. Name-based versioning could be added to the filenames, e.g. `bq_dataset_locatin_v1`, but it doesn't exist today. Versioning could also be done via subdirectories, e.g. `fixtures/assets/bq_dataset_location/v1/data.json`. Or maybe we don't need/want it.

**Comment by morgante** [comment]
Earlier, we decided that only the latest version of a constraint template will be maintained (with associated Rego file and tests). Old versions are moved into a [legacy](https://github.com/forseti-security/policy-library/pull/61) directory, where the constraint template is available but it will not be actively modified going forward.

**Comment by ddremund** [comment]
Cool, sounds good. Updated #80 to conform.

**Comment by morgante** [comment]
@t12g Does the above approach work for you too?

**Comment by abombss** [comment]
I just updated #76 to conform, I agree, I never liked the full constraint name either, the short name is much easier to work with.

**Comment by t12g** [comment]
@morgante This approach SGTM. Thanks!

**Comment by ddremund** [comment]
With the merge of #82 we can close this issue.
