### ISSUE TITLE
gcpGCPSQLAllowedAuthorizedNetworksConstraintV1:22: rego_unsafe_var_error: var _ is unsafe

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/policy-library#66]
When running the config validator as a rpc server, the following error is observed and will block the server from starting:

2019/05/23 10:11:12 Failed to load server rpc error: code = InvalidArgument desc = 1 error occurred: templates.templates.gcpGCPSQLAllowedAuthorizedNetworksConstraintV1:22: rego_unsafe_var_error: var _ is unsafe

**Comment by t12g** [comment]
This issue was present in OPA 0.10.6. It's been fixed in 0.10.7. Will need to rev the config validator library and its dependencies.
