### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by morgante** [forseti-security/policy-library#71]
We should add CI testing for all incoming pull requests. It should include:

- Running `make test` to test OPA files (unit test)
- Integrating testing with the config-validator or terraform-validator binaries to ensure templates can be successfully loaded and used

**Comment by AdrienWalkowiak** [comment]
We added the first bullet point in our CI process for this repo. I am working on a broader CI plan to cross-test code changes against the various tools dependent on the Config Validator.
