### ISSUE TITLE
User Guide | Forseti Validator

### ISSUE THREAD

**Issue by mjstatham** [forseti-security/policy-library#8]
"The one important additions is the config_validator_enabled field. It is not enabled by default; therefore you need to explicitly enable it."

Please can we reference which Forseti config file to update. Probably just easier to link to the latest [template](https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/configs/server/forseti_conf_server.yaml.sample) to make it clear.

**Comment by morgante** [comment]
Just a note that modifying the template only applies to the legacy Forseti installer - with the Terraform module, you just need to set `config_validator_enabled = true` on the module config.

We could probably make it slightly clearer though.

**Comment by AdrienWalkowiak** [comment]
I believe the [doc](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#install-forseti) is clearer now.
